# Generated by Django 2.2.1 on 2019-05-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('solicNum', models.CharField(blank=True, max_length=128)),
                ('agency', models.CharField(blank=True, max_length=128)),
                ('office', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('jobType', models.CharField(max_length=64)),
                ('origJobType', models.CharField(max_length=64)),
                ('lastPost', models.DateField()),
                ('origPost', models.DateField()),
                ('respDeadline', models.DateField()),
                ('archPolicy', models.CharField(max_length=64)),
                ('archDate', models.DateField()),
                ('setAsideType', models.CharField(max_length=64)),
                ('classCode', models.CharField(max_length=8)),
                ('NAICScode', models.IntegerField()),
                ('officeAddr', models.CharField(max_length=256)),
                ('contactInfo', models.TextField(blank=True)),
                ('placeOfPerf', models.TextField()),
                ('addInfoLink', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField()),
                ('active', models.CharField(max_length=8)),
                ('link', models.SlugField(max_length=128)),
            ],
        ),
    ]
