# Generated by Django 2.2.1 on 2019-05-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='respDeadline',
            field=models.CharField(max_length=64),
        ),
    ]
