# Generated by Django 2.2.1 on 2019-05-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opps', '0002_auto_20190524_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='archDate',
            field=models.DateField(blank=True),
        ),
    ]
