# Generated by Django 2.2.1 on 2019-05-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opps', '0003_auto_20190524_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='archPolicy',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
