# Generated by Django 2.2.1 on 2019-05-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opps', '0004_auto_20190528_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='NAICScode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='officeAddr',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='placeOfPerf',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='respDeadline',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='setAsideType',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
