# Generated by Django 2.2.1 on 2019-05-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opps', '0005_auto_20190528_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='NAICScode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='addInfoLink',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='agency',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='archDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='archPolicy',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='contactInfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='office',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='officeAddr',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='placeOfPerf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='respDeadline',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='setAsideType',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='solicNum',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
